<?php

/**
 * @file
 * Contains kms_custom.module.
 */

/**
 * Implements hook_theme().
 *
 * variables must be initialized here they will be populated in the controller
 */
function kms_custom_theme($existing, $type, $theme, $path) {
  return [
    'similar_works_block' => [
      'path' => $path . '/templates',
      'template' => 'similarWorks',
      'variables' => [
        'data' => [],
      ],
    ],
  ];
}
